INSERT INTO public.career_positions (
  slug,
  title,
  badge,
  income_label,
  description,
  schedule,
  salary,
  perks,
  status,
  show_on_listing,
  sort_order
)
VALUES
  (
    'phuc-vu-fulltime',
    'Nhân viên Phục vụ (Full-time)',
    'FULL-TIME',
    'Thu nhập: 12 - 15 Triệu/tháng',
    'Đón tiếp khách hàng, tư vấn menu món ăn, bưng bê món ăn & hỗ trợ dọn dẹp bàn tiệc chu đáo.',
    '14h30 - Hết khách',
    '7 - 9 triệu (Năng lực + Tip)',
    '["Cơ hội thăng tiến Tổ trưởng, Quản lý chi nhánh","Bao ăn 2 bữa/ngày đầy đủ dinh dưỡng","Hưởng tiền Tip, Booking, Thưởng Lễ & Thưởng doanh thu"]'::jsonb,
    'published',
    true,
    1
  ),
  (
    'phuc-vu-parttime',
    'Nhân viên Phục vụ (Part-time)',
    'PART-TIME (2 CA)',
    'Thu nhập: 5 - 8 Triệu/tháng',
    'Phục vụ bàn ăn theo ca linh hoạt, phù hợp học sinh sinh viên làm thêm thu nhập đêm.',
    'Ca 1: 14h30 - 00h00 | Ca 2: 16h00 - Hết khách',
    '5 - 8 triệu (Năng lực + Tip)',
    '["Xoay ca linh hoạt theo lịch học","Bao ăn bữa theo ca làm","Nhận tiền tip & thưởng thành tích đầy đủ"]'::jsonb,
    'published',
    true,
    2
  ),
  (
    'tiep-thuc',
    'Vị trí Tiếp thực',
    'SỐ LƯỢNG 2 NAM/NỮ',
    'Thu nhập: 6 - 8 Triệu/tháng',
    'Bao quát món ăn từ bếp ra bàn, hỗ trợ tiếp nhận món & bưng đồ cho nhân viên phục vụ nhanh chóng.',
    '17h00 - Hết khách',
    '6 - 8 triệu (Năng lực + Tip)',
    '["Môi trường làm việc nhanh nhẹn, hòa đồng","Bao ăn bữa tối","Hưởng đầy đủ tiền Tip & thưởng doanh thu"]'::jsonb,
    'published',
    true,
    3
  ),
  (
    'thu-ngan',
    'Nhân viên Thu ngân',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    'published',
    false,
    10
  ),
  (
    'phu-bep',
    'Phụ bếp / Đầu bếp Ốc Nướng',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    'published',
    false,
    11
  ),
  (
    'giu-xe',
    'Nhân viên Giữ xe / Bảo vệ',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    'published',
    false,
    12
  ),
  (
    'to-truong-ca',
    'Tổ trưởng Ca / Tạp vụ',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    'published',
    false,
    13
  );
